plugins {
    id 'java'
    id 'application'
}

group = 'org.sachith'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
}

application {
    mainClass = 'org.sachith.ClientSimulator'
}

jar {
    archiveFileName = 'bus-ticket-client.jar'

    manifest {
        attributes(
                'Main-Class': 'org.sachith.ClientSimulator'
        )
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}